---
title: "State Data Revisited"
author: "Terrel Shumway"
date: "05/02/2015"
output: html_document
---

This document presents answers for homework 4 part 4.

## Getting and Cleaning the Data

```{r}
data(state)
statedata = data.frame(state.x77)
# 
# baseurl = "https://courses.edx.org/c4x/MITx/15.071x_2/asset/"
# 
# getdata = function(local){
#   if(!file.exists(local)){
#     library(downloader)
#     remote = paste0(baseurl,local)
#     print(remote)
#     download(remote,local)
#   }
#   read.csv(local)
# }
# 
# statedata = getdata("statedataSimple.csv")

```


## Linear Regression Models
problem 1.1: 
```{r}
m1 = lm(Life.Exp ~ .,data=statedata)
s = summary(m1)
s$adj.r.squared
```

problem 1.2:
```{r}
#sum((statedata$Life.Exp-predict(m1,type="response"))^2)
sum(resid(m1)^2)
```

problem 1.3,1.4:
```{r}
m2 = step(m1)
s = summary(m2)
s$adj.r.squared
sum(resid(m2)^2)
```

## CART Models
```{r}
library(rpart)
library(rpart.plot)
```

problem 2.1:
```{r}
m3 = rpart(m1$terms,data=statedata)
prp(m3)
```

problem 2.2:
```{r}
sum((statedata$Life.Exp-predict(m3))^2)
```

problem 2.3:
```{r}
m4 = rpart(m1$terms,data=statedata,minbucket=5)
prp(m4)
```

problem 2.5:
```{r}
sum((statedata$Life.Exp-predict(m4))^2)
```

problem 2.6:
```{r}
m5 = rpart(Life.Exp~Area,data=statedata,minbucket=1)
sum((statedata$Life.Exp-predict(m5))^2)
```

## Cross Validation
```{r}
library(caret)

numFolds = trainControl(method="cv",number=10)
cpGrid = expand.grid(.cp = seq(0.01,0.5,0.01))

set.seed(111)
cvmodels = train(Life.Exp~., 
      data=statedata,
      method="rpart",
      trControl=numFolds,
      tuneGrid=cpGrid)
cvmodels$bestTune
```


```{r}
m6 = rpart(m1$terms,data=statedata,cp=cvmodels$bestTune)
prp(m6)
sum((statedata$Life.Exp-predict(m6))^2)
```


```{r}
set.seed(111)
cvmodels = train(Life.Exp~Area, 
      data=statedata,
      method="rpart",
      trControl=numFolds,
      tuneGrid=cpGrid)
cvmodels$bestTune
m7 = rpart(Life.Exp~Area,data=statedata,cp=cvmodels$bestTune)
prp(m7)
sum((statedata$Life.Exp-predict(m7))^2)
```

