---
title: "Identifying Letters ABPR"
author: "Terrel Shumway"
date: "04/25/2015"
output: html_document
---

This document presents answers to the questions of part two of homework four.

```{r}
library(caTools)
library(rpart)
library(rpart.plot)
library(randomForest)

accuracy = function(conf){sum(diag(conf))/sum(conf)}


baseurl = "https://courses.edx.org/c4x/MITx/15.071x_2/asset/"

getdata = function(local){
  if(!file.exists(local)){
    library(downloader)
    remote = paste0(baseurl,local)
    download(remote,local)
  }
  data = read.csv(local)#,stringsAsFactors=F)
  data
}

data = getdata("letters_ABPR.csv")
data$letter = as.factor(data$letter)
data$isB = data$letter=="B"


set.seed(1000)
spl = sample.split(data$isB,SplitRatio=0.5)
train = data[spl,]
test = data[!spl,]
```

## B or not B

Problem 1.1:
```{r}
accuracy = function(conf){sum(diag(conf))/sum(conf)}

bl.outcome = mean(train$isB)>0.5
bl.conf = table(test$isB,rep(bl.outcome,length=nrow(test)))
bl.acc = accuracy(bl.conf)
```
baseline accuracy = `r bl.acc`

Problem 1.2:
```{r}
m1 = rpart(isB~.-letter,data=train,method="class")

m1.pred = predict(m1,newdata=test,type="class")
m1.conf = table(test$isB,m1.pred)
m1.acc = accuracy(m1.conf)
```
model1 accuracy = `r m1.acc`

Problem 1.3:
```{r}
set.seed(1000)
m2 = randomForest(isB~.-letter,data=train)

m2.pred = predict(m2,newdata=test)
m2.conf = table(test$isB,m2.pred>0.5)
m2.acc = accuracy(m2.conf)

```
random forest accuracy = `r m2.acc`

## Predicting Letters A,B,P,R
Problem 2.1
```{r}

data$isB = NULL
set.seed(2000)
spl = sample.split(data$letter,SplitRatio=0.5)
train = data[spl,]
test = data[!spl,]


letters = table(train$letter)
bl.outcome = dimnames(letters)[[1]][which.max(letters)]
bl.conf = table(test$letter,rep(bl.outcome,length=nrow(test)))
bl.acc = accuracy(bl.conf)
```
baseline accuracy = `r bl.acc`

Problem 2.2
```{r}
m4 = rpart(letter~.,data=train,method="class")

m4.pred = predict(m4,newdata=test,type="class")
m4.conf = table(test$letter,m4.pred)
m4.acc = accuracy(m4.conf)

```

accuracy = `r m4.acc`

Problem 2.3
```{r}
set.seed(1000)
m3 = randomForest(letter~.,data=train)

m3.pred = predict(m3,newdata=test)
m3.conf = table(test$letter,m3.pred)
m3.acc = accuracy(m3.conf)

```

accuracy = `r m3.acc`