---
title: "Why People Vote"
author: "Terrel Shumway"
date: "05/02/2015"
output: html_document
---

This document presents answers for homework 4 part 1.

## Getting and Cleaning the Data
```{r}
library(data.table)

baseurl = "https://courses.edx.org/c4x/MITx/15.071x_2/asset/"

getdata = function(local){
  if(!file.exists(local)){
    library(downloader)
    remote = paste0(baseurl,local)
    print(remote)
    download(remote,local)
  }
  read.csv(local)
}

data = getdata("gerber.csv")

# this is for my sanity
data$sex = factor(data$sex)
levels(data$sex) = c("male","female")

```

## Preparing the Dataset
problem 1.1: 
```{r}
depvar="voting"
idvars = c("sex","yob")
mean(data[,depvar])
```

problem 1.2:
```{r}
# first, convert from indicator matrix to factor
# thanks to http://stackoverflow.com/users/684229/tms
# for this clever code
# http://stackoverflow.com/questions/7727315/how-to-create-a-factor-from-a-binary-indicator-matrix
groups = c("control","civicduty","hawthorne","self","neighbors")
data$stimulus = as.factor(groups[as.matrix(data[,groups]) %*% 1:length(groups)])

# get the mean of each group
sort(tapply(data$voting,data$stimulus,mean))
```

problem 1.3:
```{r}
m1 = glm(voting~stimulus,data=data,family="binomial")
summary(m1)
```

problem 1.4:
```{r}
m1.pred = predict(m1,type="response")
conf = table(data[,depvar],m1.pred>0.3)
sum(diag(conf))/nrow(data)
```

problem 1.5:
```{r}
conf = table(data[,depvar],m1.pred>0.5)
sum(diag(conf))/nrow(data)
```

problem 1.6
```{r}
library(ROCR)
pred = prediction(m1.pred,data[,depvar])
plot(performance(pred,"tpr","fpr"))
as.numeric(performance(pred,"auc")@y.values)
```

## Trees
```{r}
library(rpart)
library(rpart.plot)

```

problem 2.1
```{r}
m2 = rpart(voting~stimulus,data=data)
prp(m2)
```

```{r}
m3 = rpart(voting~stimulus,data=data,cp=0)
prp(m3)
```

problem 2.2,2.3:
```{r}
# this model is identical to `m3` above, just a different shape
m4 = rpart(voting~civicduty+hawthorne+self+neighbors,data=data,cp=0)
prp(m4)
```

problem 2.4:
```{r}
m5 = rpart(voting~stimulus+sex,data=data,cp=0)
prp(m5)
```

```{r}
# this model is identical to `m3` above, just a different shape
m6 = rpart(voting~sex+civicduty+hawthorne+self+neighbors,data=data,cp=0)
prp(m6)
```

## Interaction Terms
```{r}
P = data.frame(sex=c(0,0,1,1),control=c(0,1,0,1))
P$sex = factor(P$sex)
levels(P$sex) = c("male","female")

m7 = rpart(voting ~ control,data=data,cp=0)
#prp(m7,digits=6)
cbind(P,pred=predict(m7,newdata=P,method="response"))

m8 = rpart(voting ~ control+sex,data=data,cp=0)
#prp(m8,digits=6)
cbind(P,pred=predict(m8,newdata=P,method="response"))

```

```{r}
m9 = glm(voting~control+sex,data=data,family="binomial")

cbind(P,pred=predict(m9,newdata=P,type="response"))

m10 = glm(voting~control+sex+sex:control,data=data,family="binomial")
cbind(P,pred=predict(m10,newdata=P,type="response"))
summary(m10)
```


